import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { criteriaFile, ok, singleRepoProject, state, tmp, wf, write } from './helpers.mjs';
import { report, toHandoffCsv } from '../engine/telemetry.mjs';

// Enough TOML for generated agent files: top-level `key = "basic"` and `key = """multi-line basic"""` strings.
function parseToml(text) {
  const out = {};
  const unescape = (s) => s.replace(/\\(u[0-9a-fA-F]{4}|.)/g, (_, c) => ({ n: '\n', t: '\t', '"': '"', '\\': '\\' })[c] ?? (c[0] === 'u' ? String.fromCharCode(parseInt(c.slice(1), 16)) : assert.fail(`bad escape \\${c}`)));
  let rest = text;
  while (rest.length) {
    rest = rest.replace(/^(\s*(#[^\n]*)?\n)+/, '');
    if (!rest.trim()) break;
    const key = rest.match(/^([A-Za-z0-9_-]+) = /);
    assert.ok(key, `expected key = value at: ${rest.slice(0, 40)}`);
    rest = rest.slice(key[0].length);
    let m = rest.match(/^"""\n?((?:[^"\\]|\\[\s\S]|"(?!""))*)"""\s*(\n|$)/);
    if (!m) m = rest.match(/^"((?:[^"\\\n]|\\.)*)"[ \t]*(\n|$)/);
    assert.ok(m, `expected a string for ${key[1]}`);
    assert.equal(out[key[1]], undefined, `duplicate key ${key[1]}`);
    out[key[1]] = unescape(m[1]);
    rest = rest.slice(m[0].length);
  }
  return out;
}

const frontmatter = (file) => {
  const m = fs.readFileSync(file, 'utf8').match(/^---\n([\s\S]*?)\n---\n/);
  return Object.fromEntries(m[1].split('\n').map((l) => [l.slice(0, l.indexOf(':')), l.slice(l.indexOf(':') + 2)]));
};

test('wf sync writes one implementer per class with the class effort, Codex agents as TOML, and removes stale generated files', () => {
  const classes = { light: { codex: { effort: 'low' } }, docs: { use: 'Docs: README and guides only.', claude: { effort: 'medium', model: 'sonnet' } } };
  const { root } = singleRepoProject('classes', { classes, gate: { steps: [] } });
  write(root, '.codex/agents/wf-reviewer.md', '---\nname: wf-reviewer\n---\n<!-- generated by `wf sync` from agentic-workflow; edit .workflow/ instead -->\nold\n');
  write(root, '.codex/agents/wf-mine.md', 'hand written\n');
  ok(wf(root, ['sync']));
  const claude = (n) => frontmatter(path.join(root, '.claude/agents', `${n}.md`));
  assert.equal(claude('wf-implementer').effort, 'high', 'the implementer role defaults to class full');
  assert.equal(claude('wf-implementer-light').effort, 'low');
  assert.equal(claude('wf-implementer-docs').effort, 'medium');
  assert.equal(claude('wf-implementer-docs').model, 'sonnet');
  assert.equal(claude('wf-implementer').model, undefined, 'model stays unset unless a class sets it');
  assert.equal(claude('wf-planner').effort, 'high');
  assert.equal(claude('wf-reviewer').effort, 'high');
  assert.match(JSON.parse(claude('wf-implementer-docs').description), /Class docs: Docs: README and guides only\./);
  const light = parseToml(fs.readFileSync(path.join(root, '.codex/agents/wf-implementer-light.toml'), 'utf8'));
  assert.deepEqual(Object.keys(light).sort(), ['description', 'developer_instructions', 'model_reasoning_effort', 'name']);
  assert.equal(light.name, 'wf-implementer-light');
  assert.equal(light.model_reasoning_effort, 'low');
  assert.match(light.developer_instructions, /You are the implementer[\s\S]*work class `light`/);
  const full = parseToml(fs.readFileSync(path.join(root, '.codex/agents/wf-implementer.toml'), 'utf8'));
  assert.equal(full.model_reasoning_effort, undefined, 'no codex effort configured for full: inherit');
  parseToml(fs.readFileSync(path.join(root, '.codex/agents/wf-reviewer.toml'), 'utf8'));
  assert.equal(fs.existsSync(path.join(root, '.codex/agents/wf-reviewer.md')), false, 'old generated Codex .md agent removed');
  assert.ok(fs.existsSync(path.join(root, '.codex/agents/wf-mine.md')), 'files without the generated marker are left alone');
});

test('the adapter refuses unknown classes, undocumented efforts and the old per-role model/effort fields', () => {
  const cases = [
    [{ roles: { implementer: { class: 'heavy' } } }, /roles\.implementer\.class `heavy` is not a known class \(known: full, light\)/],
    [{ classes: { light: { claude: { effort: 'extreme' } } } }, /claude effort `extreme` is not one of low, medium, high, xhigh, max/],
    [{ classes: { light: { codex: { effort: 'max' } } } }, /codex effort `max` is not one of minimal, low, medium, high, xhigh/],
    [{ roles: { reviewer: { effort: 'high' } } }, /roles\.reviewer: effort moved to `classes`/],
    [{ classes: { docs: { claude: { effort: 'low' } } } }, /class `docs` needs `use`/],
  ];
  for (const [config, err] of cases) {
    const { root } = singleRepoProject('badclass', { ...config, gate: { steps: [] } });
    const r = wf(root, ['sync']);
    assert.notEqual(r.code, 0, JSON.stringify(config));
    assert.match(r.err, err);
  }
});

function planned(name, work, criteria = [{ id: 'C1', text: 'api' }, { id: 'C2', text: 'ui' }]) {
  const { base, root } = singleRepoProject(name, { gate: { steps: [] } });
  const e = ok(wf(root, ['entry', '--item', 'W-1', '--owner', 'o', '--json'])).json();
  ok(wf(root, ['handoff', 'planner', '--agent', 'p', '--attempt', e.id]));
  const f = path.join(base, `plan-${Math.random().toString(36).slice(2)}.json`);
  fs.writeFileSync(f, JSON.stringify({ plan: { summary: 's' }, criteria, work }));
  return { base, root, id: e.id, plan: wf(root, ['plan', '--file', f, '--attempt', e.id]) };
}

test('planner work items: unknown classes, unknown criteria and duplicate ids are refused', () => {
  const unknownClass = planned('w-class', [{ id: 'W1', criteria: ['C1'], class: 'medium' }]).plan;
  assert.notEqual(unknownClass.code, 0);
  assert.match(unknownClass.err, /class `medium` is not a known class \(known: full, light\)/);
  assert.match(planned('w-crit', [{ id: 'W1', criteria: ['C9'], class: 'light' }]).plan.err, /unknown criteria C9/);
  assert.match(planned('w-dup', [{ id: 'W1', criteria: ['C1'] }, { id: 'W1', criteria: ['C2'] }]).plan.err, /duplicate work item id W1/);
  const loose = planned('w-loose', [{ id: 'W1', criteria: ['C1'], class: 'light' }]).plan;
  assert.equal(loose.code, 0, 'an uncovered criterion is shown, not refused');
  assert.match(loose.out, /no work item covers C2/);
});

test('an implementer handoff for a work item names the agent type and records class and declared effort', () => {
  const { root, id, plan } = planned('w-hand', [{ id: 'W1', criteria: ['C2'], repos: ['app'], class: 'light', why: 'UI on the frozen contract' }, { id: 'W2', criteria: ['C1'], class: 'full', why: 'authorization' }]);
  ok(plan);
  const before = state(root, id).next;
  assert.match(before, /W1 class light \[wf-implementer-light\][\s\S]*W2 class full \[wf-implementer\]/);
  assert.match(before, /never general-purpose/);
  const h = ok(wf(root, ['handoff', 'implementer', '--work', 'W1', '--agent', 'impl-ui', '--attempt', id]));
  assert.match(h.out, /work item W1, class light, effort low/);
  assert.match(h.out, /Start agent type wf-implementer-light \(name it impl-ui; do not pass a model\)/);
  const s = state(root, id);
  const rec = s.handoffs.at(-1);
  assert.deepEqual([rec.work, rec.class, rec.effort, rec.agentType], ['W1', 'light', 'low', 'wf-implementer-light']);
  const bundle = JSON.parse(fs.readFileSync(rec.bundle, 'utf8'));
  assert.deepEqual([bundle.work.id, bundle.class, bundle.effort, bundle.agentType], ['W1', 'light', 'low', 'wf-implementer-light']);
  assert.match(s.next, /W2 class full/);
  assert.doesNotMatch(s.next, /W1 class/);
  assert.match(wf(root, ['handoff', 'implementer', '--work', 'W9', '--agent', 'x', '--attempt', id]).err, /no work item `W9`.*W1, W2/);
  ok(wf(root, ['handoff', 'implementer', '--work', 'W2', '--agent', 'impl-api', '--attempt', id]));
  assert.match(state(root, id).next, /commit the change, then hand to a fresh reviewer/);
  const plain = ok(wf(root, ['handoff', 'implementer', '--agent', 'impl-3', '--attempt', id]));
  assert.match(plain.out, /class full, effort high\nStart agent type wf-implementer /);
});

test('criteria amendments merge by id; dropping one needs an explicit marker with a reason', () => {
  const three = [{ id: 'C1', text: 'one' }, { id: 'C2', text: 'two' }, { id: 'C3', text: 'three' }];
  const { base, root, id, plan } = planned('amend', undefined, three);
  ok(plan);
  const amend = (criteria) => wf(root, ['criteria', 'amend', '--file', criteriaFile(base, criteria), '--reason', 'narrowed', '--attempt', id]);
  const r = ok(amend([{ id: 'C2', text: 'two, narrowed' }]));
  assert.match(r.out, /criteria now \(3\): C1, C2, C3\n {2}changed: C2; added: none; dropped: none/);
  assert.deepEqual(state(root, id).criteria.map((c) => c.text), ['one', 'two, narrowed', 'three']);
  assert.match(amend([{ id: 'C3', dropped: true }]).err, /dropping C3 needs a `reason`/);
  assert.match(amend([{ id: 'C3' }]).err, /C3 needs `text` \(or `dropped: true`/);
  ok(amend([{ id: 'C3', dropped: true, reason: 'moved to a follow-up' }, { id: 'C4', text: 'four' }]));
  const s = state(root, id);
  assert.deepEqual(s.criteria.map((c) => c.id), ['C1', 'C2', 'C4']);
  assert.deepEqual(s.criteriaAmendments.at(-1).changes, { changed: [], added: ['C4'], dropped: [{ id: 'C3', reason: 'moved to a follow-up' }] });
});

test('wf report reads Claude subagent transcripts by agent name and shows declared against observed effort', () => {
  const { root, id, plan } = planned('telemetry', [{ id: 'W1', criteria: ['C1', 'C2'], class: 'light' }]);
  ok(plan);
  ok(wf(root, ['handoff', 'implementer', '--work', 'W1', '--agent', 'impl-ui', '--attempt', id]));
  const home = tmp('claude-home');
  const dir = path.join(home, '.claude', 'projects', '-some-project', 'session-1', 'subagents');
  const line = (o) => JSON.stringify(o);
  const t0 = new Date(Date.now() + 1000).toISOString();
  const t1 = new Date(Date.now() + 1000 + 6 * 60000).toISOString();
  write(dir, 'agent-a1.meta.json', JSON.stringify({ agentType: 'wf-implementer-light', name: 'impl-ui' }));
  write(dir, 'agent-a1.jsonl', [
    line({ type: 'user', timestamp: t0, message: { role: 'user', content: 'Read the bundle' } }),
    line({ type: 'assistant', timestamp: t0, requestId: 'r1', effort: 'medium', message: { model: 'claude-test', usage: { input_tokens: 10, output_tokens: 5 }, content: [{ type: 'text' }] } }),
    line({ type: 'assistant', timestamp: t0, requestId: 'r1', effort: 'medium', message: { model: 'claude-test', usage: { input_tokens: 10, output_tokens: 40 }, content: [{ type: 'tool_use' }] } }),
    line({ type: 'assistant', timestamp: t1, requestId: 'r2', effort: 'medium', message: { model: 'claude-test', usage: { input_tokens: 3, output_tokens: 60 }, content: [] } }),
  ].join('\n'));
  // Same name, other agent type: not this handoff.
  write(dir, 'agent-a2.meta.json', JSON.stringify({ agentType: 'general-purpose', name: 'impl-ui' }));
  write(dir, 'agent-a2.jsonl', line({ type: 'assistant', timestamp: t0, requestId: 'x', message: { model: 'other', usage: { output_tokens: 999 } } }));
  const rows = report([root], { home });
  const h = rows[0].roles.find((x) => x.role === 'implementer');
  assert.equal(h.session, null);
  assert.deepEqual([h.work, h.class, h.declaredEffort, h.observedEffort, h.effortMismatch, h.agentType, h.model], ['W1', 'light', 'low', 'medium', true, 'wf-implementer-light', 'claude-test']);
  assert.equal(h.outputTokens, 100, 'each request counted once at its final output count');
  assert.equal(h.wallMinutes, 6);
  assert.equal(h.activeMinutes, 0, 'a gap of 5 minutes or more is idle, not work');
  const csv = toHandoffCsv(rows).trim().split('\n');
  assert.match(csv[0], /^project,id,handoff,role,agent,runtime,work,class,declaredEffort,observedEffort,effortMismatch,agentType,model,sessionModel,wallMinutes,activeMinutes,rounds,outputTokens,cost,subagents,subagentCost$/);
  assert.ok(csv.some((l) => /,implementer,impl-ui,claude,W1,light,low,medium,true,wf-implementer-light,claude-test,,6,0,1,100,,0,$/.test(l)), csv.join('\n'));
});
