#!/usr/bin/env node
// Writes CHANGELOG.md from the release notes (docs/releases/v*.md, newest first) and the improvement history
// (improvements/I-*.md: each failure, the release that fixed it and its scenario test).
//   node scripts/changelog.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ver = (s) => s.split('.').map(Number);
const newer = (a, b) => {
  const [x, y] = [ver(a), ver(b)];
  for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return y[i] - x[i];
  return 0;
};
const notes = fs.readdirSync(path.join(ROOT, 'docs', 'releases')).filter((f) => /^v\d+\.\d+\.\d+\.md$/.test(f)).map((f) => f.slice(1, -3)).sort(newer);
const items = fs.readdirSync(path.join(ROOT, 'improvements')).filter((f) => /^I-\d+\.md$/.test(f)).map((f) => {
  const text = fs.readFileSync(path.join(ROOT, 'improvements', f), 'utf8');
  return { id: f.slice(0, -3), n: Number(f.slice(2, -3)), title: /^# I-\d+: (.+)$/m.exec(text)?.[1] ?? '', fixed: /\*\*Fixed in:\*\* (.+)$/m.exec(text)?.[1] ?? '', test: /\*\*Test:\*\* (.+)$/m.exec(text)?.[1] ?? '' };
}).sort((a, b) => b.n - a.n);

const out = ['# Changelog', '', 'Release notes, newest first, then every fix that came from a failure in the workflow itself. Generated by `node scripts/changelog.mjs` from `docs/releases/` and `improvements/`.', ''];
for (const v of notes) out.push(fs.readFileSync(path.join(ROOT, 'docs', 'releases', `v${v}.md`), 'utf8').trim(), '');
out.push('## Improvement history', '', '| Item | Failure fixed | Fixed in | Scenario test |', '| --- | --- | --- | --- |');
for (const i of items) out.push(`| [${i.id}](improvements/${i.id}.md) | ${i.title} | ${i.fixed} | ${i.test.split(' (')[0]} |`);
fs.writeFileSync(path.join(ROOT, 'CHANGELOG.md'), `${out.join('\n')}\n`);
console.log(`CHANGELOG.md: ${notes.length} release(s), ${items.length} improvement(s)`);
